spring.application.name=api

# PostgreSQL Database Connection Settings
spring.datasource.url=jdbc:postgresql://localhost:5435/vaultgamedb
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# FlyAway / Migrations Settings
spring.flyway.enabled=true

#Hiraki / PoolConections Settings
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=30000

#MongoDB / NoSQL Settings
spring.data.mongodb.uri=mongodb://mongo:mongo@localhost:27015/vaultgamedbnosql?authSource=admin